# Generated by Django 4.2.3 on 2023-07-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanches',
            name='foto',
        ),
        migrations.CreateModel(
            name='ImageBurguer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto_burguer')),
                ('lanche', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.lanches')),
            ],
        ),
    ]
