# Generated by Django 4.2.3 on 2023-07-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_acompanhamento_bebidas_extra_sobremesa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acompanhamento',
        ),
        migrations.DeleteModel(
            name='Bebidas',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Sobremesa',
        ),
    ]
