# Generated by Django 4.2.3 on 2023-07-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_acompanhamento_descricao_alter_extra_descricao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acompanhamento',
        ),
        migrations.DeleteModel(
            name='Bebidas',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Sobremesa',
        ),
    ]
