# Generated by Django 4.2.3 on 2023-07-14 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_acompanhamento_bebidas_extra_sobremesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade_extra', models.IntegerField(blank=True, null=True)),
                ('quantidade_acompanhamento', models.IntegerField(blank=True, null=True)),
                ('quantidade_sobremesa', models.IntegerField(blank=True, null=True)),
                ('quantidade_bebida', models.IntegerField(blank=True, null=True)),
                ('valor', models.FloatField()),
                ('acompanhamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.acompanhamento')),
                ('bebida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.bebidas')),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.extra')),
                ('lanche', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.lanches')),
                ('sobremesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.sobremesa')),
            ],
        ),
    ]
