# Generated by Django 4.2.3 on 2023-07-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='finalizado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
