# Generated by Django 4.2.3 on 2023-07-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0001_initial'),
        ('pedidos', '0012_pedido_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='site_principal.usuario'),
            preserve_default=False,
        ),
    ]
