# Generated by Django 4.2.3 on 2023-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_pedido_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='finalizado',
            field=models.CharField(blank=True, default='NÃO', max_length=3, null=True),
        ),
    ]
