# Generated by Django 4.2.3 on 2023-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_pedido_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_acompanhamento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_bebida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_extra',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_sobremesa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
